- op: replace
  path: /spec/replicas
  value: 1

- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: DD_ENV
      value: "preproduction"
    - name: NODE_ENV
      value: "preproduction"
    - name: REDIS_URL
      value: ""

- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - containerPort: 3000

- op: add
  path: /spec/template/spec/serviceAccount
  value: solver

